### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by jpbalarini** [Rostifar/NYUDepthNet#2]
@Rostifar Hi! First, thanks for sharing your work on this project 👍 

I'm trying to run it, but I'm having some issues. You mention that there is a `main.py` file, but it's not on the repo. Also you explain an automatic and manual way of installing it, but I don't understand what I need to run to configure everything.

Thanks!

**Comment by rbriden** [comment]
Hi @jpbalarini,

I'm in the process of revamping the repository to make the build process more intuitive, so currently the latest build is failing. If you revert the repository several commits back, you'll have a working - albeit more complex- build. Sorry for the inconvenience. I should have a new, working build within the next several days.

**Comment by rbriden** [comment]
@jpbalarini I should be able to publish a working build today.

**Comment by jpbalarini** [comment]
Thanks @Rostifar for your support! Much appreciated :raised_hands:

**Comment by jpbalarini** [comment]
PD: I checked the older commits but it seems that all update the `README` file, only the initial commit has code modifying the other files.

**Comment by jpbalarini** [comment]
Hi @Rostifar, do you have any update? Is there anything I can do to help you?
Thank you!

**Comment by rbriden** [comment]
Hi @jpbalarini, I haven't had time to work on it this week because I'm still filling out college applications. I can send you the code I've been working on. It's still not functional, but it may help. I should be able to finally finish the implementation by early December. Sorry for any inconveniences.

**Comment by jpbalarini** [comment]
Hi @Rostifar don't worry I don't have any hurry! I will check in a couple of weeks and if it's still a WIP I will ask you for the code.
Thanks!

**Comment by rbriden** [comment]
Hi @jpbalarini just a small update. I should be able to release by next Wednesday, at the latest. Thanks for your patience!
